// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6NvVg1ySbdwZXnIWq12fx_JkqgpBwdoU',
    appId: '1:721759612515:web:6b5e5fd9ad4946600f5256',
    messagingSenderId: '721759612515',
    projectId: 'healthlink-8d75e',
    authDomain: 'healthlink-8d75e.firebaseapp.com',
    storageBucket: 'healthlink-8d75e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDns-3vZBMndCvRHUy6x2j-j8V2nBbw9XE',
    appId: '1:721759612515:android:c7a47106763fa2ed0f5256',
    messagingSenderId: '721759612515',
    projectId: 'healthlink-8d75e',
    storageBucket: 'healthlink-8d75e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnUYh349ebZvHhh7U8SQ2hD6dYJXoYC8w',
    appId: '1:721759612515:ios:8668a9e566c8c64d0f5256',
    messagingSenderId: '721759612515',
    projectId: 'healthlink-8d75e',
    storageBucket: 'healthlink-8d75e.firebasestorage.app',
    iosBundleId: 'com.example.nushhack',
  );

}